### ISSUE TITLE
這是要做甚麼用的?

### ISSUE THREAD

**Issue by steven0129** [CCU-sslab4ai/tensorflow-wheel#1]

**Comment by kerol2r20** [comment]
Pypi 上的 tensorflow-gpu 可能無法匹配目前使用 CUDA 或者 cuDNN 版本，因此我從原始碼編譯 tensorflow 以適合當前作業環境。

**Comment by kerol2r20** [comment]
之後如果有時間研究，可以使用 Travis CI 自動建置所需要的 build。然後自己上傳 Release 版本。

**Comment by steven0129** [comment]
不錯!!
